### ISSUE TITLE
Poise Planks do not craft Chest (Quark is installed)

### ISSUE THREAD

**Issue by OtterLan** [team-abnormals/endergetic#116]
Hello! I am not sure what is causing the problem, but i cannot seem to craft  poise chests (I am on a server). 

![image](https://user-images.githubusercontent.com/73777471/97800307-302af000-1c6f-11eb-952f-9f978806484d.png)

**Comment by SmellyModder** [comment]
There isn't a good way of fixing this yet because of recipe conflicts, but we're looking into a fix for this.

**Comment by bageldotjpg** [comment]
You can use the [Polymorph](https://www.curseforge.com/mc-mods/polymorph) mod to bypass this for the time being
