### ISSUE TITLE
Puffbugs with invisibility lose their texture

### ISSUE THREAD

**Issue by WitheredWasabi** [team-abnormals/endergetic#118]
![image](https://user-images.githubusercontent.com/38932715/97819767-82fcab80-1c5f-11eb-9874-df855d9c8c2d.png)

**Comment by SmellyModder** [comment]
Are you talking about them having no color? I'm a bit confused by the title.

**Comment by SmellyModder** [comment]
Ok, I think I've fixed it. Seems to be caused by some incompatibility.
Are you using any shaders?
