### ISSUE TITLE
Poise clusters have odd collision physics

### ISSUE THREAD

**Issue by abigailfails** [team-abnormals/endergetic#127]
https://user-images.githubusercontent.com/24257045/102820024-76c5dc80-43cc-11eb-8590-1077dea5c840.mp4

In the past you jittered around a bit while standing on a poise cluster (I assume due to being teleported), but now it's not possible to stay on it at all. Was this changed because it became impractical to keep a player on the cluster, or was it accidental?

**Comment by SmellyModder** [comment]
I believe this was a 1.16.3+ beta exclusive bug.
