### ISSUE TITLE
Mod wont load In FML Version: 1.16.1-forge-32.0.108

### ISSUE THREAD

**Issue by Nexustheninja** [team-abnormals/endergetic#132]
No sure why but the mod will not load. Also it is the only mod in the mod folder. Error message was: 

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry
Exit Code: -1

**Comment by bageldotjpg** [comment]
You need Abnormals Core for this mod to run
