### ISSUE TITLE
a few chunks in my overworld spawned as endergetic?

### ISSUE THREAD

**Issue by BumbleyBee** [team-abnormals/endergetic#136]
A few chunks in my world has spawned in as endergetic:poise_forest, all along what is suppose to be gravel beach. i came across it  as i was exploring. I haven't even been to the end yet and i got the achievement  
![image](https://user-images.githubusercontent.com/77132566/103963211-b3ad0580-5126-11eb-8f21-aa2a9006edcc.png)

**Comment by SmellyModder** [comment]
This issue is not Endergetic's fault.
When biomes get added or removed, it can cause existing generated biomes to get shifted due to biomes IDs internally getting shifted.
