### ISSUE TITLE
Crash While riding Booflo in overworld

### ISSUE THREAD

**Issue by Xander4228** [team-abnormals/endergetic#137]
Minecraft Version: 1.16.4
World type: Dedicated Server
Endergetic Version: 3.0.0
Other Mod (In case it's a conflict):
Aquaculture
Autumnity
better than llamas
better weather
clumps
create
fairy lights
embellishcraft
Macaw's [doors/bridges/furniture/windows/trapdoors]
mystical world
simple farming
sit on stairs and slabs
storage drawers
the endergetic expansion
undergarden
waystones
Notes: I can fly around in the end just fine, for as long as I want, but as soon as I'm in the overworld if I am in the air too long my game just closes with no explanation, I already enabled flying on the server, cause I was hoping that would fix my issue

**Comment by SmellyModder** [comment]
I can't do much without logs. I'm also unable to reproduce this issue.
