### ISSUE TITLE
Corrocks don't generate waterlogged underwater

### ISSUE THREAD

**Issue by WenXin20** [team-abnormals/endergetic#138]
`Minecraft v1.16.4`
`Forge v35.1.36`
`Endergetic v3.0.0`

I added the corrocks to the `minecraft:coral_plants` tag in my personal datapack to allow it to generate in coral reefs, but most of the time they do not generate waterlogged. A minor bug, but could this be fixed?

**Comment by SmellyModder** [comment]
What kind of corrock blocks? Also, can you send a screenshot?

**Comment by WenXin20** [comment]
The normal & crowns of all three dimension types.

Here's an End Corrock:
![2021-01-10_20 44 27](https://user-images.githubusercontent.com/12000593/104143364-bdcc3f80-5384-11eb-8c41-ccfc53b02155.png)

**Comment by SmellyModder** [comment]
This is caused by vanilla's coral generation only using default waterlogged states. This isn't really an endergetic issue, but I can fix it by making waterlogged true by default for corrock blocks.

**Comment by WenXin20** [comment]
Ah, alright, thanks.

**Comment by WenXin20** [comment]
I've noticed that this isn't fixed, but I'm guessing there's not really anything else that can be done.
