### ISSUE TITLE
Additional Quark compatibility

### ISSUE THREAD

**Issue by COMBOhrenovke** [team-abnormals/endergetic#150]
Quark has a feature called Campfires Boost Elytra and its wiki description is:

> When flying using an Elytra over a Campfire with a Hay Bale under it, the player will be propelled upwards slightly.
> 1.16.3+ Only: Soul Campfires will have the opposite effect, pulling you quickly towards the ground.

Ender Campfires fully function with this already, but don't do something interesting and have the same effect as normal Campfires.

So, I am asking you to make Ender Campfires also do something different than the normal Campfire. My idea for this behaviour is that as propelling upwards and downwards are already taken, the Ender Campfire should propel you forwards. This also has a lore explanation as flying forward fast is similar to teleportation which is one of main properties that some ender mobs in vanilla have.

Additionally, besides survival use for this mechanic, it could be used in Elytra course maps. The original console edition ones had ways to propel you both up and forward so maps made with use of campfires would be able to do much the same. The only big drawbacks and differences would be the particles emitted from campfires and the fact that you could burn yourself on them, but that's easily avoided by disabling particles in game settings and giving the player fire resistance effect.

So all in all, a pretty useful feature in many use cases and one just nice to have.

**Comment by SmellyModder** [comment]
Interesting idea, but not really a goal for Ender Campfires.
Ender Campfires were added for quark compatibility and will probably stay that way forever.
