### ISSUE TITLE
Vibra jungle & chorus forest

### ISSUE THREAD

**Issue by ManagerGibbon24** [team-abnormals/endergetic#155]
When are these announced biomes going to see the light of day?

**Comment by SmellyModder** [comment]
This is not an issue.
We don't give ETAs.

**Comment by ManagerGibbon24** [comment]
I just wanted to know, when these biomes will be added, if you don't want to tell me, please tell me if you're working on them.

**Comment by ManagerGibbon24** [comment]
> This is not an issue.
> We don't give ETAs.

Then please tell me if you are working on them

**Comment by PercyJames** [comment]
> This is not an issue. We don't give ETAs.

sorry for digging up a long dead thing but where do i find the announcements?
