### ISSUE TITLE
Abnormals Core 3.1.0 breaks the boofalo vest

### ISSUE THREAD

**Issue by MossyMossMoss** [team-abnormals/endergetic#156]
When using Abnormals Core 3.1.0, you cannot use the boofalo vest's inflate ability. I tested with Abnormals Core 3.0.6 and it worked with that

**Comment by SmellyModder** [comment]
I'm unable to reproduce this issue with Abnormals Core 3.1.0
Make sure there aren't any keys conflicting with the Booflo Vest

**Comment by Cinderheart** [comment]
I'm having the same issue.

**Comment by SmellyModder** [comment]
Try changing the keybind and see if it works. If it works, then there's a key conflict.

**Comment by Cinderheart** [comment]
isn't it just the jump button? I'm not seeing any specific keybind for it.

**Comment by SmellyModder** [comment]
It's space by default. The keybind is called `Booflo Vest Activate`.
