### ISSUE TITLE
[1.16.5] Excessive Puff Bug reproduction

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/endergetic#168]
Puff Bugs are travelling around from their hive and for some reason reproducing a lot, while flying away from their nest. There were 20 last time I used the kill command to clear them out, just hovering around the area of the hive, though they seem happy to roam outside the area, getting unloaded and tricking the existing Puff Bugs into creating more babies:   
https://i.imgur.com/TLt3fHZ.jpg

This is where the hive is, in the top of a Poise tree (with some gaps to allow them to get out and pollinate the flowers):  
https://i.imgur.com/jCRMir8.jpg  
There were 20 hovering around the tree before using the kill command, all from a single hive.

**Comment by SmellyModder** [comment]
This is *sorta* intentional.
Puff Bugs are meant to roam around from their hive to find more Bolloom Buds because they can be more sparse in Poise Forests.
Puff Bugs will attempt to breed *randomly* if their hive isn't at max capacity.
Because of Minecraft's entity loading system, the hives can't always be 100% sure of the Puff Bugs that belonged to it when some Puff Bugs get unloaded.
When Puff Bugs are in a more open area, I suggest encasing them in a glass cage so they can't wander far.

**Comment by MarioSMB** [comment]
Ah, that is a shame - would you consider adding an option or a gamerule to disable their random reproducing, as a workaround? I can of course encase them, this just seems like an issue that has massive lag potential (for example if one lived in the poise forest - something I am actually planning to do).

**Comment by HMSCelestia** [comment]
This is a more serious problem while running a server, as multiple hives will all begin spawing puffs that already exist with the same UUID. This causes lots of rapidfire UUID collisions that the server has to deal with, leading to a severe drop in performance.

**Comment by MarioSMB** [comment]
I too would like to see this revisited - the limitations of Minecraft do not necessarily justify intentionally allowing creatures to procreate infinitely.  
It took several rounds of using the /kill command to seemingly remove all of the puff bugs from around our base, and even then one can't be sure without checking everywhere... a gamerule to control puff bug reproduction would be greatly appreciated.

**Comment by Enterprise12nx01** [comment]
i got to the end in 1.19.2 and im getting the same crash referencing these mobs
