### ISSUE TITLE
Log spam "Received balloons for unknown entity!"

### ISSUE THREAD

**Issue by aaronhowser1** [team-abnormals/endergetic#170]
![image](https://user-images.githubusercontent.com/15698722/114382539-1660d380-9b52-11eb-99bc-7b0cd077d185.png)

It shows up 582 times in my latest.log, and 
[latest.log](https://github.com/team-abnormals/endergetic/files/6295925/latest.log)

This is using `endergetic-1.16.4-3.0.0` on Forge 36.1.4

**Comment by SmellyModder** [comment]
This isn't necessarily an issue we can fix.
The `Received balloons for unknown entity` is a log warning given when the client can't find the entity a specific set of balloons is supposed to be attached to.
If the warning is recurring many times, this implies a deeper desyncing issue with entity ids.
Vanilla has a similar log warning built-in that says `Received passengers for unknown entity`.
