### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Johnny100HD** [team-abnormals/endergetic#173]
So after i defeated the dragon, my game always crashes when I am at the poise forest. Unfortunately I can't keep on playing in this world because everytime I load in the game, it crashes because I already am in the poise forest! It would be really nice, if you could fix it because I have so many hours in that world:( 

I am playing in the "Just Another Vanilla Upgraded" Modpack by dreams01 and the mod version is 1.15.2-v1.3.2, if you need that information for conflicting mods or whatever.

Thank you in advance!

**Comment by SmellyModder** [comment]
I cannot do much without a crash report.

**Comment by Johnny100HD** [comment]
Oh yes, of course! Sorry.
[crash-2021-05-14_10.33.47-server.txt](https://github.com/team-abnormals/endergetic/files/6480644/crash-2021-05-14_10.33.47-server.txt)

**Comment by SmellyModder** [comment]
Looks like an issue caused by the Extra Bows mod.
Extra Bows' source code is not public, so I cannot explain why the crash happens, but it has something to do with `BridgeUpgrade`.
It'd be best to report this issue to them, but first try removing Extra Bows and see if the crash no longer happens.

**Comment by Johnny100HD** [comment]
Oh thank you so much. i am sorry for wasting your time:(

**Comment by SmellyModder** [comment]
Looks like there is a similar issue on their GitHub already: https://github.com/MrMarnic/ExtraBows/issues/47
