### ISSUE TITLE
Ender Campfire Incompatible With Healing Campfire & No Hostiles Around Campfire

### ISSUE THREAD

**Issue by Brittank88** [team-abnormals/endergetic#174]
This is in reference to ricksouth/serilum-mc-mods#491.

[This is the line that checks for campfires in the world in their code.](https://github.com/ricksouth/serilum-mc-mods/blob/c13dab4cc570779a46262e8f9200db4c876b166f/sources/Healing%20Campfire/src/main/java/com/natamus/healingcampfire/events/CampfireEvent.java#L55)

[This is the function itself, that checks for, in this case, TileEntities of type `TileEntityType.CAMPFIRE`.](https://github.com/ricksouth/serilum-mc-mods/blob/c13dab4cc570779a46262e8f9200db4c876b166f/sources/Collective/src/main/java/com/natamus/collective/functions/FABFunctions.java#L41)

I can see that in Endergetic, the Ender Campfire does extend from the `CampfireTileEntity` class. However, it seems it doesn't count as `TileEntityType.CAMPFIRE` still, because it isn't being picked up by the function I linked to above. Other campfires from other mods (such as BYG) work just fine, which is the main reason why I figured I should post an issue here too.

**Comment by SmellyModder** [comment]
This is an issue on their side.
It's not wise to assume every tile entity campfire in a modded environment will be of type `TileEntityType.CAMPFIRE`.
A better method of determining campfires would be to use the `minecraft:campfires` block tag to lessen chances for incompatibilities and give datapack makers the ability to decide which blocks should be affected.

**Comment by Brittank88** [comment]
Agreed. Very, very agreed.
