### ISSUE TITLE
Incompatible with Java Version of Adopt Open JDK8 OpenJ9

### ISSUE THREAD

**Issue by Blunder-G** [team-abnormals/endergetic#184]
Crash with Adopt Open JDK8 OpenJ9.

Produce:

1 - Install Adopt Open JDK8 OpenJ9. link: https://adoptopenjdk.net
2 - Go to launcher and find JVM Arguments
3 - Browse and find "javaw" (I can tell other steps that i don't say)
4 - Download Endergetic
5 - Launch game
6 - Error (Crash)

**Comment by SmellyModder** [comment]
Endergetic does not explicitly support OpenJ9.
1.17 Minecraft, which will be coming soon, requires Java 16.
