### ISSUE TITLE
Create Crash?

### ISSUE THREAD

**Issue by A1Enigma** [team-abnormals/endergetic#186]
This issue is not only for endergetic expansion, but almost every single team Aurora or abnormals mod. On launch, the game (or server in my case) crashes because Create failed to load properly. If you need anything else, like a log or mod list, I can provide that.

**Comment by SmellyModder** [comment]
Are you using the latest version of Create?

**Comment by SmellyModder** [comment]
I'm going to assume the issue you are having is related to https://github.com/team-abnormals/abnormals-core/issues/112
The latest version of Create should work correctly with the latest version of Abnormals Core.
If the issue persists after updating Create, then I will look further into this issue.
