### ISSUE TITLE
Crash due to 'Ticking entity' upon entering Poise Forest (1.16.5)

### ISSUE THREAD

**Issue by ChrissCross717** [team-abnormals/endergetic#191]
https://pastebin.com/kSGiQkBf

Title pretty much sums it up. Mod list attached within crash report. Worlds are unretrievable without resetting the End as re-entering the world after a crash promptly leads into another crash. Not sure if this is due to mod incompatibilities or something specifically on Endergetic's end (pun not intended).

**Comment by SmellyModder** [comment]
Same as #190
