### ISSUE TITLE
(Minor) "Poise Wood" should be called "Poise Hyphae"

### ISSUE THREAD

**Issue by artemisSystem** [team-abnormals/endergetic#193]
For consistency with other wood/fungus types

Wood follows the pattern:
Oak Log/Oak Wood

Fungus follows the pattern:
Warped Stem/Warped Hyphae

Poise is currently:
Poise Stem/Poise Wood

Should be:
Poise Stem/Poise Hyphae

**Comment by SmellyModder** [comment]
This is known.
Poise is not technically a fungus nor necessarily a 'normal' tree.
