### ISSUE TITLE
End Portal & End Gateways not generating after resetting The End (deleting DIM1 file)

### ISSUE THREAD

**Issue by Gijsko** [team-abnormals/endergetic#194]
Whenever the DIM1 file is removed from the world folder so chunks can regenerate, the end portal and end gateways will no longer generate.

**Comment by SmellyModder** [comment]
Deleting just the `DIM1` file is not enough to properly and safely reset the end.
This issue describes a safe way to reset the end: https://github.com/AllTheMods/ATM-6/issues/437

**Comment by SteamDoge9000** [comment]
Hello, I looked at the link and desided to try something out of random, and by shear luck, It was a fix wtihout having todo anything super complex

all you have todo is simple

using a NBT data view like NBTexplorer open the worlds affected level.data and go into the forge entries and then open one called enddragonfight or something close to that

im not exacaly sure what one done it but by setting these 3 values to zero the game understood (but the mod mostly) recognized an issue and treats the end dim as the first time being loaded in, this in turn caused the frame that does not regenerate during a dim 1 delete. this in fact caused the frame to regenerate
