### ISSUE TITLE
Error Adding Element causing periodic server lag spikes

### ISSUE THREAD

**Issue by IdealIdeas** [team-abnormals/endergetic#197]
Endergetic 1.16.4 - 3.0.0
forge-1.16.5-36.2.2

ERROR:
[main/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Base value out of range: 256 [-10-128]

I get exactly 9 of this error anytime I boot the server. Then it periodically spits this error out as I play the server causing the server to suffer from pretty hard lag spikes.

Once I remove the mod and boot the server, the server doesnt get 9 of these errors and it doesnt crop up while playing in the server either.

**Comment by SmellyModder** [comment]
https://github.com/team-abnormals/endergetic/issues/175
