### ISSUE TITLE
[1.16.5-3.0.0] Corrock Tower Configuredfeature cannot be parsed and turned to json

### ISSUE THREAD

**Issue by TelepathicGrunt** [team-abnormals/endergetic#201]
When using Endergetic Expansion with Blame on, Blame reports in the log that the Corrock Tower configuredfeature is unabled to be turned back into json (typically for mod compat). https://paste.ee/p/t6egG

The issue is the 256 for count method is too large for the count codec which is limited to -10 to 128. Instead, a simple solution is to swap `func_242731_b(256)` with `withPlacement(Placement.COUNT_EXTRA.configure(new AtSurfaceWithExtraConfig(256, 0F, 0)))` since the count extra placement does not have any limit
https://github.com/team-abnormals/endergetic/blob/5b9ca8ca2ba65c3697df858fa90f7f10716d4e10/src/main/java/com/minecraftabnormals/endergetic/common/world/features/EEFeatures.java#L68

Hope this helps!

**Comment by SmellyModder** [comment]
Duplicate of https://github.com/team-abnormals/endergetic/issues/175
