### ISSUE TITLE
Invisible, angry puff bug

### ISSUE THREAD

**Issue by phcgamer** [team-abnormals/endergetic#203]
I was trying to set up a bollom farm in a modpack, and needed puff bugs. I tried replacing the hive when I didn't know if the bugs were linked to it, and learned they were when they attacked me. I bottled all but one of them up. That one was on the ground when I tried to bottle it, but it just turned invisible. Help?

**Comment by SmellyModder** [comment]
You may have been experiencing a possible desync issue where the client thought the Puff Bug was there but was actually at a different position.
Unfortunately, this isn't something we can fix.
