### ISSUE TITLE
[1.16.5server]Wrong biome spawn

### ISSUE THREAD

**Issue by Theagree** [team-abnormals/endergetic#204]
![image](https://user-images.githubusercontent.com/84651172/147402697-872f69ce-58bb-4b0c-90af-0859e027d930.png)
if i install this mod and Apotheosis mod at the same time , normal mob will spawn in end such as creepers zombies. i think it is because of the biome where mobs spawning is a normal world biome.
useing server [LoliServer-1.16.5-eac7eaf-server.jar]

**Comment by Theagree** [comment]
![image](https://user-images.githubusercontent.com/84651172/147402791-fbf161fe-cc7c-41aa-b4e1-cf0a329c00b8.png)
and normal mobs will not spawn in endergetic biome

**Comment by Theagree** [comment]
abnormals core 3.3.0
endergetic 3.0.0

apotheosis 4.8.4
placebo 4.6.1
 forge 36.2.22

**Comment by SmellyModder** [comment]
It appears that your biome IDs have shifted somehow, which is not Endergetic's fault.
What can happen is that the registration order of biomes can change, leading to some areas having incorrect biomes.
