### ISSUE TITLE
Suicidal Boofloos

### ISSUE THREAD

**Issue by StrangerSon71** [team-abnormals/endergetic#205]
Boofloos do not appear to be attempting to stay near their owner at all, which makes keeping them very hard. Holding their breeding food did not seem to help. This has gone to the extent of one dying to the void.

**Comment by SmellyModder** [comment]
Booflos do not follow their owner, like a Horse. Booflos are not attracted to bolloom fruit after they are tamed.
Using a lead or building a cage are nice ways to keep a Booflo in the same place.

**Comment by StrangerSon71** [comment]
So... Useless for exploration. Issue of them going into void still stands.
