### ISSUE TITLE
Endergetic biomes incompatible with BYG/ BOP ? No biomes generating

### ISSUE THREAD

**Issue by p256ah** [team-abnormals/endergetic#210]
I own a server that has both Biomes o' plenty, and BYG (Biomes you'll go), and I can't find any of the Endergetic biomes. I've manually searched about a 100k block radius from the spawn end island, and I've started using the "Natures compass" mod, and with a search radius of 100,000k blocks, still cannot find any of the biomes. I haven't read anywhere that these two mods are incompatible, but am I wasting my time searching, because they wont generate? 

Also, the end portal is revamped (with the new blocks), so the mod affects the spawn end island, but other than that, nothing else generates.

**Comment by SmellyModder** [comment]
Endergetic adds its biomes to the end using [Blueprint](https://www.curseforge.com/minecraft/mc-mods/blueprint)'s end biome system.
I'm not familiar with how Biomes o' Plenty and BYG add their end biomes in 1.16.5, but if they are doing it in an incompatible way, that's their issue.
