### ISSUE TITLE
[1.16.5 - 3.0.1] Crash after killed ender dragon

### ISSUE THREAD

**Issue by Kzeroko** [team-abnormals/endergetic#211]
After killing ender dragon, world crashed with this report.
https://pastebin.com/HNwYfJ3V

**Comment by GoldenFlame0** [comment]
Can confirm this happens to me as well with a very similar looking crash log.

**Comment by nc5432** [comment]
This same issue happened to me. It says that the remote gateway portal has an issue with ticking entities. This occurs in the 3.0.1 version but not the 3.0.0 version, so if you downgrade it will work.

**Comment by SmellyModder** [comment]
Correct, this is caused by a small mistake we made when porting to Mojang Mappings.

**Comment by bageldotjpg** [comment]
Fixed https://www.curseforge.com/minecraft/mc-mods/endergetic/files/3750371
