### ISSUE TITLE
[Question] Are you almost done with updating the mod to 1.18.2, or are you skipping to 1.19?

### ISSUE THREAD

**Issue by StormDragon-64** [team-abnormals/endergetic#216]
Hey, I was wondering if you were going to update the mod to 1.18.2 soon, because I noticed you finally updated your other mods but not this one. Are you almost done with the 1.18.2 version, or are you skipping to 1.19?

**Comment by SmellyModder** [comment]
Read this: https://www.teamabnormals.com/blog/1-18-releases-and-1-19-info
