### ISSUE TITLE
[Question] : How come you stopped updating this mod? It was one of the best End improving mods out there!

### ISSUE THREAD

**Issue by RandomGuy91** [team-abnormals/endergetic#243]

**Comment by Cixon** [comment]
Real. I would love to include this mod in my 1.18.2 pack and I'm many others would love a 1.20.1 port!

**Comment by TheTimvh1** [comment]
I am not a member of TeamAbnormals, but please understand that they have not stopped updating the mod.  It simply isn't ready for public release just yet.  Don't forget they have a ton of mods under their belt, many of them being quite large in terms of content, and they only have so many people to work on them.  Plus there is real life that must be taken into account, in addition to the constant changes in the base game's code whenever a major update occurs.  There is a 1.19.2 beta available for patreon subscribers, but know that the mod is not dead.  Please have patience.  Thank you.

**Comment by RandomGuy91** [comment]
Well, they update all their other mods within a few weeks of the game updating, and the last public update on this mod is 1.16 (and hasn't been updated for a year) They are not struggling to update their other mods, and I was only ASKING why they stopped updating this one, on top of giving no reason as to why.  Also, I am not pressing them or acting angry or frustrated, so I don't know why you thought I was being impatient. Thank you.

**Comment by Cixon** [comment]
Real. The modding community just gets curious; we aren’t impatient, we just love this mod
