### ISSUE TITLE
Is 1.20.1 coming eventually?

### ISSUE THREAD

**Issue by CheezBallzFTW** [team-abnormals/endergetic#261]
Just wondering if I should wait or if it's not being worked on.

**Comment by SmellyModder** [comment]
It's not currently being worked on, and we have no plans to do so for 1.20.1.
Due to the speed at which Mojang is updating the game these days, we are now focused on porting to 1.21+.
However, Endergetic can only receive porting work once Blueprint is ported to 1.21.
